enum JavaScriptNodeType {
  ARRAY,
  ASSIGNMENT_OPERATION,
  BINARY_OPERATION,
  BOOLEAN,
  CONSOLE_LOG_STATEMENT,
  FUNCTION_CALL,
  FUNCTION_DEFINITION,
  IIFE,
  NULL,
  NUMBER,
  STRING,
  CONDITIONAL_OPERATION,
  VARIABLE,
}

export default JavaScriptNodeType;
